### ISSUE TITLE
Stye index 

### ISSUE THREAD

**Issue by jeremiahlukus** [mayapozzolo/railsCollabNovel#1]
the stying is bad

**Comment by jeremiahlukus** [comment]
What the prob??

**Comment by mayapozzolo** [comment]
Will work on!

**Comment by jeremiahlukus** [comment]
Hey i shave this explain?

```ruby
<%= render 'sharded/navbar %>

```

**Comment by jeremiahlukus** [comment]
```ruby 
<li> hey </li>

```

**Comment by jeremiahlukus** [comment]
# hey

**Comment by mayapozzolo** [comment]
~~~ ruby <h3> Hello </h3> ~~~

**Comment by jeremiahlukus** [comment]
Google markdown lang, its what the readme is


`

**Comment by mayapozzolo** [comment]
``` ruby <h3> Hello </h3> ```

**Comment by jeremiahlukus** [comment]
.md files stand for markdown

**Comment by jeremiahlukus** [comment]
```ruby

**Comment by mayapozzolo** [comment]
``` ruby
<h5> Welcome </h5>
```

**Comment by jeremiahlukus** [comment]
When you start working on this again do "gco -b" foloowed by what you are going to do an example: ` gco - b setup-blog ` 
once you finish what you are doing then 

`acp "Setup blog views an added comment feature" `

then 

gco master

git merge setup-blog 


then you can go on github and merge the changes on there. If you are ever working on a project with someone this is the normal process.

**Comment by jeremiahlukus** [comment]
gco -b  means git checkout -branch   usually you do not push to master if you are working with people to avoid errors.
