### ISSUE TITLE
Generate home about and contact page

### ISSUE THREAD

**Issue by jeremiahlukus** [mayapozzolo/railsCollabNovel#2]
Generate the pages home about contact and copy the html you have already wrote into them

`rails g controller Pages home about contact`

**Comment by jeremiahlukus** [comment]
also go through as many of the udemy lectures as you can try to finish section 3 before we meet again. The first section you can mostly breeze through.

**Comment by mayapozzolo** [comment]
Sounds good!  Just finished adding 
```ruby
git browser-remote
```
 :)

**Comment by jeremiahlukus** [comment]
Once you finish an "issue" close it.

**Comment by mayapozzolo** [comment]
For Fonts and Colours do I still use the style sheet in Collabnovel or is it done through rails?

**Comment by mayapozzolo** [comment]
Is it in Veiw?

**Comment by jeremiahlukus** [comment]
You still use the stylesheet to change appearances.

**Comment by jeremiahlukus** [comment]
A common font is railway check out Google fonts

**Comment by mayapozzolo** [comment]
Hmm my stylesheet is empty did we remove everything?

**Comment by jeremiahlukus** [comment]
In the Rails app we didn't style anything

**Comment by mayapozzolo** [comment]
oh ok so it's in rails not the original css file?

**Comment by jeremiahlukus** [comment]
https://github.com/mayapozzolo/CssLearning/commit/2766f0c25f3c4577fee47574d22805f5fe3a6219

It seems like you deleted it on accident? 
Luckily you pushed it to github
